project_id = "siotixqzwlfcrseveiwd"

[functions.test-stripe-connection]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.residence-assistant]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true
